import { TokenName } from 'crypto-token-icon';
import {
    airiOraichain,
    atomOraichain,
    aUSDTOraichain,
    btcOraichain,
    injOraichain,
    kwtOraichain,
    milkyOraichain,
    ntmpiOraichain,
    ochOraichain,
    oraiOraichain,
    oraiXOraichain,
    osmoOraichain,
    scATOMOraichain,
    scINJOraichain,
    scORAIOraichain,
    scOSMOOraichain,
    sORAIOraichain,
    stOSMOOraichain,
    tonOraichain,
    usdcOraichain,
    usdtOraichain,
    wethOraichain,
    wTRXOraichain,
} from '.';

export const mapNameToInfoOraichain = {
    [TokenName.ORAI]: oraiOraichain,
    [TokenName.ATOM]: atomOraichain,
    [TokenName.OSMO]: osmoOraichain,
    [TokenName.USDC]: usdcOraichain,
    [TokenName.scOSMO]: scOSMOOraichain,
    [TokenName.scATOM]: scATOMOraichain,
    [TokenName.KWT]: kwtOraichain,
    [TokenName.MILKY]: milkyOraichain,
    [TokenName.NTMPI]: ntmpiOraichain,
    [TokenName.TON]: tonOraichain,
    [TokenName.BTC]: btcOraichain,
    [TokenName.AIRI]: airiOraichain,
    [TokenName.ORAIX]: oraiXOraichain,
    [TokenName.USDT]: usdtOraichain,
    [TokenName.aUSDT]: aUSDTOraichain,
    [TokenName.sORAI]: sORAIOraichain,
    [TokenName.scORAI]: scORAIOraichain,
    [TokenName.stOSMO]: stOSMOOraichain,
    [TokenName.WTRX]: wTRXOraichain,
    [TokenName.INJ]: injOraichain,
    [TokenName.scINJ]: scINJOraichain,
    [TokenName.OCH]: ochOraichain,
    [TokenName.WETH]: wethOraichain,
};

export type TOraichainToken = keyof typeof mapNameToInfoOraichain;

export const findTokenNameOraichain: Record<string, TOraichainToken> = {
    [oraiOraichain.address]: TokenName.ORAI,
    [atomOraichain.address]: TokenName.ATOM,
    [osmoOraichain.address]: TokenName.OSMO,
    [ntmpiOraichain.address]: TokenName.NTMPI,
    [tonOraichain.address]: TokenName.TON,
    [airiOraichain.address]: TokenName.AIRI,
    [oraiXOraichain.address]: TokenName.ORAIX,
    [usdtOraichain.address]: TokenName.USDT,
    [aUSDTOraichain.address]: TokenName.aUSDT,
    [sORAIOraichain.address]: TokenName.sORAI,
    [scORAIOraichain.address]: TokenName.scORAI,
    [scATOMOraichain.address]: TokenName.scATOM,
    [stOSMOOraichain.address]: TokenName.stOSMO,
    [scOSMOOraichain.address]: TokenName.scOSMO,
    [kwtOraichain.address]: TokenName.KWT,
    [milkyOraichain.address]: TokenName.MILKY,
    [usdcOraichain.address]: TokenName.USDC,
    [wTRXOraichain.address]: TokenName.WTRX,
    [injOraichain.address]: TokenName.INJ,
    [scINJOraichain.address]: TokenName.scINJ,
    [ochOraichain.address]: TokenName.OCH,
    [btcOraichain.address]: TokenName.BTC,
    [wethOraichain.address]: TokenName.WETH,
};
